2022-07-09T01:43:11.262Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-07-09T01:43:11.294Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-07-09T01:43:11.428Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-07-09T01:56:21.909Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-07-09T01:56:21.915Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-07-09T01:56:21.926Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-07-09T02:10:36.796Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-07-09T02:10:36.801Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-07-09T02:10:36.813Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
2022-07-09T02:15:10.016Z	debug	1.3.0@a2d6c4b	Initializing API credentials	{"file": "/chainlink/apicredentials"}
2022-07-09T02:15:10.022Z	info	1.3.0@a2d6c4b.RunNode	Starting Chainlink Node 1.3.0 at commit a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966	{"Version": "1.3.0", "SHA": "a2d6c4b47d62ac792a215b3a8d3acfe3ae9a2966"}
2022-07-09T02:15:10.034Z	error	1.3.0@a2d6c4b	Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)	{"err": "Cannot boot Chainlink: opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)", "errVerbose": "opening db: failed to open db: failed to connect to `host=chainlink-rinkeby-pg_chainlink-1 user=postgres database=chainlink-rinkeby`: hostname resolving error (lookup chainlink-rinkeby-pg_chainlink-1 on 127.0.0.11:53: no such host)\nCannot boot Chainlink\ngithub.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode\n\t/chainlink/core/cmd/local_client.go:53\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173\ngithub.com/urfave/cli.(*App).RunAsSubcommand\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405\ngithub.com/urfave/cli.Command.startApp\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277\nmain.Run\n\t/chainlink/core/main.go:25\nmain.main.func1\n\t/chainlink/core/main.go:18\ngithub.com/smartcontractkit/chainlink/core/recovery.ReportPanics\n\t/chainlink/core/recovery/recover.go:17\nmain.main\n\t/chainlink/core/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581", "sentryEventID": null}
